waveform_base.py

Bugfix for #9. np.ndarray.view will raise a ValueError if data_2d is not C-contiguous, [as mentioned here](https://www.numpy.org/devdocs/reference/generated/numpy.ndarray.view.html). Using .real and .imag seems more robust. ~I don't know if this always does a deep copy, but I hope that python will detect if a shallow copy is possible~. EDIT: There is no deep copy, see [this example](https://github.com/moble/scri/issues/9#issuecomment-494516167)

Use .real and .imag instead of .view(dtype=float) in case of slicing

---

__init__.py
mode_calculations.py
requirements.txt
waveform_modes.py

This is baseline code which uses Simpson's rule from scipy.integrate.simps for quadrature. A better approach would be to use interpolation, but this will require using a wrapper function that @moble wrote for `quaternion`

General inner product functionality in mode_calculations

---

__init__.py
mode_calculations.py
tests/test_mode_calculations.py

All three of these have expressions in terms of quadratic combinations of the modes of h, which sandwich some linear operators. All those operators are sparse in the SWSH basis, so they can be computed in O(N) where N is the number of modes. This is accomplished with a higher order function `matrix_expect_val(a, M, b)`, which computes <a|M|b>. The matrix M is defined in terms of a generator `M(ell_min, ell_max)` which is then iterable, yielding tuples `(ellp, mp, ell, m, M_el)` that correspond to non-vanishing matrix elements <ellp, mp|M|ell, m>.

Add fluxes of E, P, J, via a general matrix-expectation-value function

---

waveform_base.py

Pickling and unpickling a WaveformBase object doesn't work.  The
problem resides in the class variable `WaveformBase.__num`, which gets
name mangled to `_WaveformBase__num` because of python conventions.  The
current `__getstate__`/`__setstate__` pair try to avoid copying
`_WaveformBase__num` in order to preserve the auto-incremented counter
`__num`, which is automatically set in `__init__`. However, pickle does
something funny that I don't fully understand, so `_WaveformBase__num`
ends up not being a member unless it *is* copied. Minimal breaking
example below.
The fix is to let `__init__` auto-increment `__num`; then upon entering
`__setstate__`, store this value in a temp, update the `__dict__`, which
overwrites `__num`, but then revert `__num` to the temp.
Minimal breaking example …

Bugfix: _WaveformBase__num needs to be included for pickling

---

waveform_base.py

When printing a WaveformModes object, the data was misaligned with the labels. This correctly aligns the data with the correct label.

Fix mislabeled elements in repr

---

tests/conftest.py

See
https://docs.pytest.org/en/latest/deprecations.html#calling-fixtures-directly
for details on the deprecation. The fixture-generating functions:
constant_wavform
linear_waveform
random_waveform
delta_waveform
were designed to be general and take optional arguments. Only their
default version should be considered as fixtures, because otherwise
they need to be called directly.  But, pytest has deprecated direct
calling of fixtures.  Therefore we make 0-argument fixtures (with
explicit names given to the decorator) which return the default values
from the above fixture-generating functions.  Then the underlying
functions can still be called with optional arguments.

Make fixture-generating funcs work again after pytest deprectation

---

waveform_grid.py

Adds extends the functionality of the BMS transformation to all the Weyl scalars. Allows the user to select which eth convention to use.

Add BMS transformation for all Weyl scalars

---

extrapolation.py

SpEC's extraction procedure has been optimized for Psi1 and Psi0 waveforms. This involves having the innermost extraction radius moved to a MUCH smaller radius (2 reduced GW wavelengths as determined by the initial data). The outermost extraction has not changed. 
Since Psi1 and Psi0 fall off as r^-4 and r^-5, the amplitude of even their dominant mode will fall beneath the error tolerance of SpEC within the extraction region. To optimize the extrapolation for these quantities, we find which outer radii on a given time slice will have a waveform value beneath a user-set tolerance. These outer radii will then be excluded from being used in extrapolation.

Exclude insignificant outer radii from Psi1 and Psi0 extrapolation

---

scri/asymptotic_bondi_data/constraints.py
scri/asymptotic_bondi_data/from_initial_values.py
scri/asymptotic_bondi_data/transformations.py
scri/modes_time_series.py

This just sets the conventions for the constraint equations to Moreschi-Boyle for the `AsymptoticBondiData` class. A later PR will introduce a function to load waveforms into an `ABD` object and convert between conventions.

Set ABD internal conventions to Moreschi-Boyle

---

tests/test_waveform_grid.py

This fixes Issue #44.
Instead of overcomplicating the test, we'll take it that `scri.sample_waveforms.single_mode_proportional_to_time_supertranslated()` operates with the assumption that all other Weyl scalars are zero. However, we still need to pass in empty `scri.WaveformModes` objects into the transformation function of `scri.sample_waveforms.single_mode_proportional_to_time()`.

Fix broken tests in test_waveform_grid.py

---

scri/waveform_grid.py

The numerical waveforms produced by SpEC are made dimensionless by scaling by the Christodoulou mass computed early in the simulation. This value should be treated as Lorentz invariant. This PR only needs to change the transformation for `WaveformModes` and `WaveformGrid` objects because the `AsymptoticBondiData` interface assumes the quantites are dimensionful (or that the Christodoulou mass is Lorentz invariant). 
The primary argument for this is from @moble. The following plot shows the value of the Christodoulou mass over the course of the simulation along with a prediction from  [arxiv:gr-qc/0107080](https://arxiv.org/abs/gr-qc/0107080). Here we have the Lev6 mass value (averaged between T=2000 and 5000), and added the integrated change in mass.

Treat the Christodoulou mass as Lorentz invariant

---

tests/test_SpEC.py

There is still a failing test `test_file_io` in `test_SpEC.py`. Depending on if the user has installed the dependencies from conda-forge or from conda, `f2["History.txt"][()]` is a byte-string or a string. Unfortunately, this means that the test will fail in one case and pass in another. This should ensure that the test will pass regardless of dependencies used.

Decode bytes into string before assert, if needed

---

scri/extrapolation.py

When you run extrapolation with barely sufficient number of radii the following error warning was triggered.
`ERROR: Asking for extrapolation up to order 4, but only got 5finite-radius Waveform objects; need at least 5 waveforms.`
This PR fixes the consistency check.

Fix error message about insufficient number of finite-radius objects

---

.github/workflows/automated_testing.yml

There was a critical bug in PR #51: it would only use the currently available version of scri on conda-forge (i.e. upstream master) to run the tests. I used the line:
```
conda install -c conda-forge scri
```
to be a quick & easy way to install the dependencies, but I forgot to install the current branch of scri on top of that.

Fix Github only running pytest on upstream master

---

scri/SpEC/__init__.py
scri/SpEC/file_io/__init__.py
scri/asymptotic_bondi_data/__init__.py
scri/asymptotic_bondi_data/bms_charges.py
scri/asymptotic_bondi_data/transformations.py
scri/extrapolation.py
scri/mode_calculations.py
scri/modes_time_series.py
scri/utilities.py
scri/waveform_base.py
scri/waveform_grid.py
scri/waveform_modes.py
setup.py
tests/test_SpEC.py
tests/test_abd_ivp.py
tests/test_asymptoticbondidata.py
tests/test_waveform_grid.py

This PR has many feature updates to the AsymptoticBondiData (ABD) class:
- Adds a function to easily create an ABD from H5 files.
- Adds the following BMS charges to ABD:
- Bondi rest mass
- Angular momentum
- dimensionless spin
- boost charge
- comoving center-of-mass charge
- supermomentum
- Tests have been added for each BMS charge
- Adds `ABD.copy()` and `ABD.interpolate(new_times)`
- Adds frame infrastructure to ABD to prepare for a future PR in which rotations will be added to ABD.
- Adds `grid_multiply` to ModesTimeSeries for faster products between MTS objects. This is implemented in `ABD.supermomentum` to speed up the function.
- Overall formatting & cleanup has been done.

Add several features to ABD

---

README.md
docs/index.rst
docs/tutorial_abd.rst
docs/tutorial_extrapolation.rst
docs/tutorial_waveformmodes.rst
scri/SpEC/com_motion.py
scri/SpEC/file_io/__init__.py

This adds three tutorials to ReadTheDocs:
- Using the `AsymptoticBondiData` class
- Using the `WaveformModes`/`WaveformGrid` class
- Performing extrapolation
These tutorials are not exhaustive but provide enough information to get a new user started.

Add tutorials to ReadTheDocs

---

.gitignore
scri/waveform_modes.py

The input data array can get manipulated internally by `WaveformModes`.    
This is now mentioned in the documentation.
Also, gotta have .swp in .gitignore.

Explain that waveforms use references to original data

---

scri/extrapolation.py

In extrapolation.py, read_finite_radius_waveform checks for non-monotonic timesteps in the input finite-radius data, and removes these non-monotonic timesteps.  Unfortunately:
1) It removes the timesteps correctly from the time array, but removes them incorrectly for the waveform data, causing a "cannot broadcast input array from shape BLA1 into shape BLA2" error whenever it actually removes non-monotonic timesteps.
2) It neglects to remove those same non-monotonic timesteps from the frame data, leading to similar shape-mismatch errors down the line.
This PR fixes both the above bugs.

Bugfix in removing non-monotonic time steps before extrapolating.

---

.github/workflows/build.yml
scri/SpEC/com_motion.py

Various changes to CoM correction to handle matter:
* Now handles NSNS as well as BHNS
* Reads correct fields from Matter.h5 (which was standardized after the previous CoM version)
* Does not assume Horizons.h5 and Matter.h5 have the same timesteps, but **does** assume that the first N timesteps (for some N) of Matter.h5 and Horizons.h5 are the same, and it cuts off subsequent timesteps.  This is because Matter.h5 is not always output at late times, e.g. for BHNS where the BH swallows the NS.

Center of mass correction for matter

---

docs/tutorial_abd.rst
scri/SpEC/file_io/__init__.py
scri/__init__.py
scri/asymptotic_bondi_data/__init__.py

Update the ``create_abd_from_h5`` function to include other post-processing, i.e., time translate by the worldtube radius, scale out the total Christodoulou mass to make waveforms dimensionless, interpolate on to some coarser time array, and map to some reasonable BMS frame. Documentation in docs/tutorial_abd.rst has also been updated.

Update ``create_abd_from_h5`` to include other post-processing options; update documentation

---

scri/SpEC/file_io/__init__.py
scri/utilities.py
tests/test_waveform_grid.py

@moble should be an easy review; fixes a bug that occurs when the output CCE data has time steps with differences ~1e-15, which are set to zero when doing `-= float(radius)` and screw up the monotonicity of the time array.

Add 2nd monotonic requirement; fixes subtle bug affecting some CCE outputs

---

scri/extrapolation.py

As simple as that, there was a missing print statement for this validation case.

extrapolation: Print the error for the mode data validation

---

.readthedocs.yaml

RTD has changed the requirements of their .readthedocs.yaml files. Either sphinx.configuration or mkdocs.configuration is mandatory.

Update RTD conf: now need a sphinx.configuration key [skip ci]

---

scri/asymptotic_bondi_data/__init__.py
scri/asymptotic_bondi_data/map_to_superrest_frame.py

Hi @moble, @duetosymmetry, and @keefemitman. I added the slicing option to the abd data which would be useful for my project. Please review the PR and let me know if there are any comments.

Adding slicing to the abd data
